References:
1. https://machinelearningmastery.com/how-to-model-human-activity-from-smartphone-data/
2. https://machinelearningmastery.com/evaluate-machine-learning-algorithms-for-human-activity-recognition/


In [11]:

# spot check on engineered-features
from pandas import read_csv
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [12]:
# load dataset
from numpy import dstack
from pandas import read_csv

# load a single file as a numpy array
def load_file(filepath):
    dataframe = read_csv(filepath, header=None, delim_whitespace=True)
    return dataframe.values
 
def load_dataset_group(group, prefix=''):
    # load input data
    X = load_file(prefix + group + '/X_'+group+'.txt')
    # load class output
    y = load_file(prefix + group + '/y_'+group+'.txt')
    return X, y

In [13]:
# load the dataset, returns train and test X and y elements
def load_dataset(prefix=''):
    # load all train
    trainX, trainy = load_dataset_group('train', prefix + 'HARDataset/')
    print(trainX.shape, trainy.shape)
    # load all test
    testX, testy = load_dataset_group('test', prefix + 'HARDataset/')
    print(testX.shape, testy.shape)
    # flatten y
    trainy, testy = trainy[:,0], testy[:,0]
    print(trainX.shape, trainy.shape, testX.shape, testy.shape)
    return trainX, trainy, testX, testy
# load dataset
trainX, trainy, testX, testy = load_dataset()
# load all train
print(trainX.shape, trainy.shape)
# load all test
print(testX.shape, testy.shape)

(7352, 561) (7352, 1)
(2947, 561) (2947, 1)
(7352, 561) (7352,) (2947, 561) (2947,)
(7352, 561) (7352,)
(2947, 561) (2947,)


In [14]:
trainX

array([[ 0.28858451, -0.02029417, -0.13290514, ..., -0.84124676,
         0.17994061, -0.05862692],
       [ 0.27841883, -0.01641057, -0.12352019, ..., -0.8447876 ,
         0.18028889, -0.05431672],
       [ 0.27965306, -0.01946716, -0.11346169, ..., -0.84893347,
         0.18063731, -0.04911782],
       ...,
       [ 0.27338737, -0.01701062, -0.04502183, ..., -0.77913261,
         0.24914484,  0.04081119],
       [ 0.28965416, -0.01884304, -0.15828059, ..., -0.78518142,
         0.24643223,  0.02533948],
       [ 0.35150347, -0.01242312, -0.20386717, ..., -0.78326693,
         0.24680852,  0.03669484]])

In [15]:
# SVM model (Dan Li)
from sklearn import svm
from pandas import read_csv
import time
from sklearn.metrics import confusion_matrix,accuracy_score, recall_score, precision_score, f1_score
def svm_model(trainX, trainy, testX, testy):
    # Step1: finding best params
    # ml = svm.SVC()
    # # setting different kernel by change the value of parameter 'kernel'
    # param_grid = {'C': [1, 10, 100, 1000, 10000],
    #               'kernel': ['sigmoid']}
    # grid = GridSearchCV(ml, param_grid, refit=True, verbose=1, cv=15)
    # # fitting the model for grid search
    # grid_search = grid.fit(trainX, trainy)
    # best_params = grid_search.best_params_
    # print(grid_search.best_params_)


    # Step2: train and predict model by best params
    # setting different kernel by change the value of parameter 'kernel'
    model = svm.SVC(kernel='linear', C=1)
    model.fit(trainX, trainy)
    train_y_predict = model.predict(trainX)
    print("training accuracy: ", end=" ")
    print(accuracy_score(trainy, train_y_predict))
    print("training recall: ", end=" ")
    print(recall_score(trainy, train_y_predict, average='macro'))
    print("training precision: ", end=" ")
    print(precision_score(trainy, train_y_predict, average='macro'))
    print("training f1 score: ", end=" ")
    print(f1_score(trainy, train_y_predict, average='macro'))
    print("___________________________________________________________________________________")
    test_y_predict = model.predict(testX)
    print("test accuracy: ", end=" ")
    print(accuracy_score(testy, test_y_predict))
    print("test recall: ", end=" ")
    print(recall_score(testy, test_y_predict, average='macro'))
    print("test precision: ", end=" ")
    print(precision_score(testy, test_y_predict, average='macro'))
    print("test f1 score: ", end=" ")
    print(f1_score(testy, test_y_predict, average='macro'))

    # Step3: plot confusion matrix
    # cm = confusion_matrix(testy, test_y_predict, labels=model.classes_)
    # disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=model.classes_)
    # disp.plot()
    # plt.show()
start = time.time()
svm_model(trainX, trainy, testX, testy)
end = time.time()
print("The time of execution of above program is :", end - start)

training accuracy:  0.9938792165397171
training recall:  0.9943671744302657
training precision:  0.9943439381310409
training f1 score:  0.9943551382036183
___________________________________________________________________________________
test accuracy:  0.9640312181879878
test recall:  0.9635891623206801
test precision:  0.9658952454847611
test f1 score:  0.9641983433163016
The time of execution of above program is : 5.095134973526001


In [21]:
# Logistic Regression Model Fitting
from sklearn.linear_model import LogisticRegression

lr_clf = LogisticRegression(solver='liblinear', random_state=0)
lr_clf.fit(trainX, trainy)

train_y_predict = lr_clf.predict(trainX)
print("training accuracy: ", end=" ")
print(accuracy_score(trainy, train_y_predict))
print("training recall: ", end=" ")
print(recall_score(trainy, train_y_predict, average='macro'))
print("training precision: ", end=" ")
print(precision_score(trainy, train_y_predict, average='macro'))
print("training f1 score: ", end=" ")
print(f1_score(trainy, train_y_predict, average='macro'))
print("___________________________________________________________________________________")
test_y_predict = lr_clf.predict(testX)
print("test accuracy: ", end=" ")
print(accuracy_score(testy, test_y_predict))
print("test recall: ", end=" ")
print(recall_score(testy, test_y_predict, average='macro'))
print("test precision: ", end=" ")
print(precision_score(testy, test_y_predict, average='macro'))
print("test f1 score: ", end=" ")
print(f1_score(testy, test_y_predict, average='macro'))

from sklearn.metrics import classification_report
import numpy as np
target_names = ["WALKING", "WALKING_UPSTAIRS", "WALKING_DOWNSTAIRS", "SITTING","STANDING","LAYING"]
print(testy)
print(test_y_predict)
print(classification_report(testy, test_y_predict, target_names=target_names))

training accuracy:  0.9908868335146899
training recall:  0.9915843179726277
training precision:  0.9915650783040765
training f1 score:  0.9915746342665867
___________________________________________________________________________________
test accuracy:  0.9619952494061758
test recall:  0.961304111284811
test precision:  0.964348966367584
test f1 score:  0.9620880741556027
[5 5 5 ... 2 2 2]
[5 5 5 ... 2 2 2]
                    precision    recall  f1-score   support

           WALKING       0.94      1.00      0.97       496
  WALKING_UPSTAIRS       0.97      0.95      0.96       471
WALKING_DOWNSTAIRS       1.00      0.97      0.98       420
           SITTING       0.97      0.88      0.92       491
          STANDING       0.90      0.97      0.94       532
            LAYING       1.00      1.00      1.00       537

          accuracy                           0.96      2947
         macro avg       0.96      0.96      0.96      2947
      weighted avg       0.96      0.96      0

In [ ]:
# create a dict of standard models to evaluate {name:object}
def define_models(models=dict()):
    # nonlinear models
    models['knn'] = KNeighborsClassifier(n_neighbors=7)
    models['cart'] = DecisionTreeClassifier()
    models['svm'] = SVC()
    models['bayes'] = GaussianNB()
    # ensemble models
    models['bag'] = BaggingClassifier(n_estimators=100)
    models['rf'] = RandomForestClassifier(n_estimators=100)
    models['et'] = ExtraTreesClassifier(n_estimators=100)
    models['gbm'] = GradientBoostingClassifier(n_estimators=100)
    print('Defined %d models' % len(models))
    return models

In [ ]:
# evaluate a single model
def evaluate_model(trainX, trainy, testX, testy, model):
    # fit the model
    model.fit(trainX, trainy)
    # make predictions
    yhat = model.predict(testX)
    # evaluate predictions
    accuracy = accuracy_score(testy, yhat)
    return accuracy * 100.0

In [ ]:
# evaluate a dict of models {name:object}, returns {name:score}
def evaluate_models(trainX, trainy, testX, testy, models):
    results = dict()
    for name, model in models.items():
        # evaluate the model
        results[name] = evaluate_model(trainX, trainy, testX, testy, model)
        # show process
        print('>%s: %.3f' % (name, results[name]))
    return results

In [ ]:
# print and plot the results
def summarize_results(results, maximize=True):
    # create a list of (name, mean(scores)) tuples
    mean_scores = [(k,v) for k,v in results.items()]
    # sort tuples by mean score
    mean_scores = sorted(mean_scores, key=lambda x: x[1])
    # reverse for descending order (e.g. for accuracy)
    if maximize:
        mean_scores = list(reversed(mean_scores))
    print()
    for name, score in mean_scores:
        print('Name=%s, Score=%.3f' % (name, score))

In [ ]:
# get model list
models = define_models()
# evaluate models
results = evaluate_models(trainX, trainy, testX, testy, models)
# summarize results
summarize_results(results)